### ISSUE TITLE
discussion: cut greenhouse scene because too many bugs?

### ISSUE THREAD

**Issue by majaguenther** [AlexInABox/grow-green#208]
- greenhouse scene very buggy :(
- easier to either cut completely or
- show in demo/readme but no option to buy, only earn = he wont get there

PRO:
- no one has to waste precious time on bugfixes

CONTRA:
- benjamin wont like
- what if he sees this issue :o
- current greenhouse work is kinda wasted

**Comment by AlexInABox** [comment]
beta mindset...
![omori-omori-my-time-lyrics](https://github.com/user-attachments/assets/9f5e4c36-3485-42cc-b1ff-40c17962bda5)
